import Foundation

/// Rules for clipboard content that must never enter history.
/// Persisted as an editable JSON file so users can extend the lists.
public struct IgnoreRules: Codable, Equatable {
    /// Pasteboard types that mark content as sensitive or machine-generated.
    public var pasteboardTypes: [String]
    /// Copies made while one of these apps is frontmost are skipped.
    public var appBundleIDs: [String]

    public init(pasteboardTypes: [String], appBundleIDs: [String]) {
        self.pasteboardTypes = pasteboardTypes
        self.appBundleIDs = appBundleIDs
    }

    public static let `default` = IgnoreRules(
        pasteboardTypes: [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "com.typeit4me.clipping",
            "de.petermaurer.TransientPasteboardType",
        ],
        appBundleIDs: []
    )

    public func shouldIgnore(types: [String], frontmostBundleID: String?) -> Bool {
        if types.contains(where: pasteboardTypes.contains) { return true }
        if let bundleID = frontmostBundleID, appBundleIDs.contains(bundleID) {
            return true
        }
        return false
    }

    /// Loads rules from `url`, writing the defaults there first if the file
    /// doesn't exist yet — so users always have a file they can edit.
    public static func load(from url: URL) -> IgnoreRules {
        if let data = try? Data(contentsOf: url),
           let rules = try? JSONDecoder().decode(IgnoreRules.self, from: data) {
            return rules
        }
        let rules = IgnoreRules.default
        if let data = try? JSONEncoder().encode(rules) {
            try? data.write(to: url, options: .atomic)
        }
        return rules
    }
}
